import React from 'react';
import {StyleSheet} from "react-native";
import {DataTable} from 'react-native-paper';

const SimpleTable = (props) => {
    return (
        <DataTable>
            <DataTable.Header>
                <DataTable.Title>Name</DataTable.Title>
                <DataTable.Title>Favourite Food</DataTable.Title>
                <DataTable.Title>Age</DataTable.Title>
            </DataTable.Header>
            <DataTable.Row>
                <DataTable.Cell>Radhika</DataTable.Cell>
                <DataTable.Cell>Sandwich</DataTable.Cell>
                <DataTable.Cell>23</DataTable.Cell>
            </DataTable.Row>
            <DataTable.Row>
                <DataTable.Cell>Radhika</DataTable.Cell>
                <DataTable.Cell>Sandwich</DataTable.Cell>
                <DataTable.Cell>23</DataTable.Cell>
            </DataTable.Row>
            <DataTable.Row>
                <DataTable.Cell>Radhika</DataTable.Cell>
                <DataTable.Cell>Sandwich</DataTable.Cell>
                <DataTable.Cell>23</DataTable.Cell>
            </DataTable.Row>
            <DataTable.Row>
                <DataTable.Cell>Radhika</DataTable.Cell>
                <DataTable.Cell>Sandwich</DataTable.Cell>
                <DataTable.Cell>23</DataTable.Cell>
            </DataTable.Row>
            <DataTable.Row>
                <DataTable.Cell>Radhika</DataTable.Cell>
                <DataTable.Cell>Sandwich</DataTable.Cell>
                <DataTable.Cell>23</DataTable.Cell>
            </DataTable.Row>
            <DataTable.Row>
                <DataTable.Cell>Radhika</DataTable.Cell>
                <DataTable.Cell>Sandwich</DataTable.Cell>
                <DataTable.Cell>23</DataTable.Cell>
            </DataTable.Row>
            <DataTable.Row>
                <DataTable.Cell>Radhika</DataTable.Cell>
                <DataTable.Cell>Sandwich</DataTable.Cell>
                <DataTable.Cell>23</DataTable.Cell>
            </DataTable.Row>
            <DataTable.Row>
                <DataTable.Cell>Radhika</DataTable.Cell>
                <DataTable.Cell>Sandwich</DataTable.Cell>
                <DataTable.Cell>23</DataTable.Cell>
            </DataTable.Row>
            <DataTable.Row>
                <DataTable.Cell>Radhika</DataTable.Cell>
                <DataTable.Cell>Sandwich</DataTable.Cell>
                <DataTable.Cell>23</DataTable.Cell>
            </DataTable.Row>
            <DataTable.Row>
                <DataTable.Cell>Radhika</DataTable.Cell>
                <DataTable.Cell>Sandwich</DataTable.Cell>
                <DataTable.Cell>23</DataTable.Cell>
            </DataTable.Row>
            <DataTable.Row>
                <DataTable.Cell>Radhika</DataTable.Cell>
                <DataTable.Cell>Sandwich</DataTable.Cell>
                <DataTable.Cell>23</DataTable.Cell>
            </DataTable.Row>
            <DataTable.Row>
                <DataTable.Cell>Radhika</DataTable.Cell>
                <DataTable.Cell>Sandwich</DataTable.Cell>
                <DataTable.Cell>23</DataTable.Cell>
            </DataTable.Row>
            <DataTable.Row>
                <DataTable.Cell>Radhika</DataTable.Cell>
                <DataTable.Cell>Sandwich</DataTable.Cell>
                <DataTable.Cell>23</DataTable.Cell>
            </DataTable.Row>
            <DataTable.Row>
                <DataTable.Cell>Radhika</DataTable.Cell>
                <DataTable.Cell>Sandwich</DataTable.Cell>
                <DataTable.Cell>23</DataTable.Cell>
            </DataTable.Row>
            <DataTable.Row>
                <DataTable.Cell>Radhika</DataTable.Cell>
                <DataTable.Cell>Sandwich</DataTable.Cell>
                <DataTable.Cell>23</DataTable.Cell>
            </DataTable.Row>
            <DataTable.Row>
                <DataTable.Cell>Radhika</DataTable.Cell>
                <DataTable.Cell>Sandwich</DataTable.Cell>
                <DataTable.Cell>23</DataTable.Cell>
            </DataTable.Row>
            <DataTable.Row>
                <DataTable.Cell>Radhika</DataTable.Cell>
                <DataTable.Cell>Sandwich</DataTable.Cell>
                <DataTable.Cell>23</DataTable.Cell>
            </DataTable.Row>
            <DataTable.Row>
                <DataTable.Cell>Radhika</DataTable.Cell>
                <DataTable.Cell>Sandwich</DataTable.Cell>
                <DataTable.Cell>23</DataTable.Cell>
            </DataTable.Row>
            <DataTable.Row>
                <DataTable.Cell>Radhika</DataTable.Cell>
                <DataTable.Cell>Sandwich</DataTable.Cell>
                <DataTable.Cell>23</DataTable.Cell>
            </DataTable.Row>
            <DataTable.Row>
                <DataTable.Cell>Radhika</DataTable.Cell>
                <DataTable.Cell>Sandwich</DataTable.Cell>
                <DataTable.Cell>23</DataTable.Cell>
            </DataTable.Row>
            <DataTable.Row>
                <DataTable.Cell>Radhika</DataTable.Cell>
                <DataTable.Cell>Sandwich</DataTable.Cell>
                <DataTable.Cell>23</DataTable.Cell>
            </DataTable.Row>
            <DataTable.Row>
                <DataTable.Cell>Radhika</DataTable.Cell>
                <DataTable.Cell>Sandwich</DataTable.Cell>
                <DataTable.Cell>23</DataTable.Cell>
            </DataTable.Row>
        </DataTable>
    );
}
export default SimpleTable;